[deps]
pytorch = "==1.13.1"
torchmetrics = "==0.7.2"
pytorch-lightning = "==1.6.0"
hydra-core = "==1.3.0"

[pip.deps]
lfads-torch = "@https://github.com/arsedler9/lfads-torch/archive/refs/tags/v1.1.0.zip"
