#!/bin/bash

# ? This script produces all figures from the full set of "data/calculations" files.
# ? It expects that you have already run the following scripts:
# 1. `scripts/calculations/download_data.jl`
# 2. `scripts/calculations/session_selection.jl`
# 3. `scripts/calculations/cluster/power_spectra.jl`
# 4. `scripts/calculations/calculations.jl`
# 5. `scripts/calculations/collect_calculations.jl`
# 6. `scripts/calculations/posthoc_session_filter.jl`
# 7. `scripts/calculations/unify_calculations.jl`

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
chmod -R u+x "$DIR/scripts/plots/"

start=$(date +%s)


echo "Producing Fig. 1"
"$DIR/scripts/plots/fig1.jl"

echo "Producing Fig. 2"
"$DIR/scripts/plots/fig2.jl"

echo "Producing Fig. 3"
"$DIR/scripts/plots/fig3.jl"

echo "Producing Fig. 4"
"$DIR/scripts/plots/fig4.jl"

echo "Producing Fig. 5"
"$DIR/scripts/plots/fig5.jl"

echo "Producing Fig. 6"
"$DIR/scripts/plots/fig6.jl"

echo "Producing Fig. S3"
"$DIR/scripts/plots/figS3.jl"

end=$(date +%s)
elapsed=$((end - start))
minutes=$((elapsed / 60))
echo "All figures combined took $minutes minutes."