#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
chmod -R u+x "$DIR/scripts/plots/"

"$DIR/scripts/plots/fig1.jl"
"$DIR/scripts/plots/fig2.jl"
"$DIR/scripts/plots/fig3.jl"
"$DIR/scripts/plots/fig4.jl"
"$DIR/scripts/plots/fig5.jl"
"$DIR/scripts/plots/fig6.jl"
