name = "SpatiotemporalMotifs"
uuid = "171a676f-b549-4f99-bec7-f4305cd3cef0"
authors = ["brendanjohnharris <brendanjohnharris@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"
